### ISSUE TITLE
Typo error in function capture_time_posted

### ISSUE THREAD

**Issue by rohitkalva** [dan-grant-hunter/indeed-scraper#1]
There's a typo error in the function capture_time_posted which breaks the code during the first iteration. 

`results = soup.select('span[class*="date "]')` needs to be changed to `results = soup.select('span[class*="date"]')`

**Comment by dan-grant-hunter** [comment]
Hmm... 

The span class in dev tools shows a space and seems to run fine on my end.

![span-class-date](https://user-images.githubusercontent.com/68550783/93015536-94f49300-f5ba-11ea-81b4-afbc835f80a4.png)

Yet, when I remove the space, it still works fine. 

Thanks for spotting this. I will update to prevent others from running into the same problem.
